import React from 'react';
import { TextField, Box, Button, Collapse, FormHelperText } from '@mui/material';
import EditIcon from '@mui/icons-material/Edit';
import CheckIcon from '@mui/icons-material/Check';
import tileStyles from '../Tile.module.css';
import styles from './EpiRisk.module.css';

const PathogenEditor = ({
  tempPositivityRate,
  handlePositivityRateChange,
  handleBlur,
  getMinPositivityRate,
  getMaxPositivityRate,
  pathogen,
  state,
  dispatch,
  quantaRate,
  handleQuantaRateChange,
  handleQuantaRateBlur,
  halfLife,
  handleHalfLifeChange,
  handleHalfLifeBlur
}) => {
  const [isExpanded, setIsExpanded] = React.useState(false);

  return (
    <Box 
      className={`${styles['pathogen-editor']} ${isExpanded ? styles['expanded'] : ''}`}
      style={{ width: isExpanded ? 'auto' : 'fit-content' }}
    >
      <Box display="flex" alignItems="center" justifyContent="center" mb={1}>
        <Button
          onClick={() => setIsExpanded(!isExpanded)}
          startIcon={isExpanded ? <CheckIcon /> : <EditIcon />}
          className={styles['edit-button']}
          variant="text"
          size="small"
        >
          {isExpanded ? 'Done' : 'Edit Pathogen'}
        </Button>
      </Box>

      <Collapse in={isExpanded}>
        <Box 
          display="flex" 
          flexDirection="column" 
          className={styles['editor-params']} 
          gap={1}
        >
          <Box flex={1}>
            <TextField
              className={tileStyles['tile-text-field']}
              label="Positivity Rate (%)"
              value={tempPositivityRate}
              onChange={handlePositivityRateChange}
              onBlur={handleBlur}
              type="number"
              inputProps={{ 
                min: getMinPositivityRate(), 
                max: getMaxPositivityRate(),
                step: 5
              }}
              fullWidth
              variant="outlined"
              size="small"
            />
            <FormHelperText className={styles['helper-text']}>
              The percentage of the population that is infectious. This value determines how many people in the space are actively spreading the pathogen.
            </FormHelperText>
          </Box>

          <Box flex={1}>
            <TextField
              className={tileStyles['tile-text-field']}
              label="Pathogen Name"
              value={state.pathogens[pathogen].name}
              onChange={(e) => {
                dispatch({
                  type: 'UPDATE_PATHOGEN',
                  payload: {
                    pathogenId: pathogen,
                    updates: { name: e.target.value }
                  }
                });
              }}
              fullWidth
              variant="outlined"
              size="small"
            />
            <FormHelperText className={styles['helper-text']}>
              Specify the name of the pathogen.
            </FormHelperText>
          </Box>

          <Box flex={1}>
            <TextField
              className={tileStyles['tile-text-field']}
              label="Infectious Doses Per Hour"
              type="number"
              value={quantaRate}
              onChange={handleQuantaRateChange}
              onBlur={handleQuantaRateBlur}
              inputProps={{ 
                min: 1, 
                step: 25 
              }}
              fullWidth
              variant="outlined"
              size="small"
            />
            <FormHelperText className={styles['helper-text']}>
              The number of infectious doses generated by one infected person per hour. This represents how many units of infection an infectious person releases into the air, which affects transmission risk.
            </FormHelperText>
          </Box>

          <Box flex={1}>
            <TextField
              className={tileStyles['tile-text-field']}
              label="Half-life (hours)"
              type="text"
              value={halfLife}
              onChange={handleHalfLifeChange}
              onBlur={handleHalfLifeBlur}
              inputProps={{ 
                min: 0.0001,
                max: 24,
                step: 0.0001
              }}
              fullWidth
              variant="outlined"
              size="small"
            />
            <FormHelperText className={styles['helper-text']}>
              The time it takes for half of the airborne pathogen particles to become inactive. A shorter half-life means the pathogen loses infectivity more quickly in the air.
            </FormHelperText>
          </Box>
        </Box>
      </Collapse>
    </Box>
  );
};

export default PathogenEditor; 